"""add foreign key for book

Revision ID: 5638ba871c10
Revises: e37b12340f1d
Create Date: 2024-11-03 16:08:34.239493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5638ba871c10"
down_revision: Union[str, None] = "e37b12340f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "user_id")
    # ### end Alembic commands ###
